src/Entity/Produit.php
<?php

namespace App\Entity;

use Monolog\DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $promo;

    /**
     * @ORM\Column(type="string")
     */
    private $taille;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_custom;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="produits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\ManyToMany(targetEntity=Skateboard::class, mappedBy="composer")
     */
    private $skateboards;

    /**
     * @ORM\OneToMany(targetEntity=Etoile::class, mappedBy="produit", orphanRemoval=true)
     */
    private $etoiles;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="produit", orphanRemoval=true)
     */
    private $commentaires;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    public function __construct()
    {
        $this->skateboards = new ArrayCollection();
        $this->etoiles = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->created_at = new DateTimeImmutable('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getPromo(): ?int
    {
        return $this->promo;
    }

    public function setPromo(?int $promo): self
    {
        $this->promo = $promo;

        return $this;
    }

    public function getTaille(): ?string
    {
        return $this->taille;
    }

    public function setTaille(string $taille): self
    {
        $this->taille = $taille;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getIsCustom(): ?bool
    {
        return $this->is_custom;
    }

    public function setIsCustom(bool $is_custom): self
    {
        $this->is_custom = $is_custom;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection<int, Skateboard>
     */
    public function getSkateboards(): Collection
    {
        return $this->skateboards;
    }

    public function addSkateboard(Skateboard $skateboard): self
    {
        if (!$this->skateboards->contains($skateboard)) {
            $this->skateboards[] = $skateboard;
            $skateboard->addComposer($this);
        }

        return $this;
    }

    public function removeSkateboard(Skateboard $skateboard): self
    {
        if ($this->skateboards->removeElement($skateboard)) {
            $skateboard->removeComposer($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Etoile>
     */
    public function getEtoiles(): Collection
    {
        return $this->etoiles;
    }

    public function addEtoile(Etoile $etoile): self
    {
        if (!$this->etoiles->contains($etoile)) {
            $this->etoiles[] = $etoile;
            $etoile->setProduit($this);
        }

        return $this;
    }

    public function removeEtoile(Etoile $etoile): self
    {
        if ($this->etoiles->removeElement($etoile)) {
            // set the owning side to null (unless already changed)
            if ($etoile->getProduit() === $this) {
                $etoile->setProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setProduit($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getProduit() === $this) {
                $commentaire->setProduit(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function __toString(): string{
        return $this->nom;
    }

    public function getAverageEtoiles(){
        $average = 0;
        $etoiles = $this->getEtoiles()->toArray();
        if(count($etoiles) == 0 ){
            return 0;
            die();
        }
        foreach ($etoiles as $etoile) {
            $average += $etoile->getNote();
        }
        return round($average / count($etoiles), 2);
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $prenom;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $newletter;

    /**
     * @ORM\OneToMany(targetEntity=Adresse::class, mappedBy="user", orphanRemoval=true)
     */
    private $adresses;

    /**
     * @ORM\ManyToMany(targetEntity=Produit::class)
     */
    private $wishlist;

    /**
     * @ORM\OneToMany(targetEntity=Commande::class, mappedBy="user")
     */
    private $commandes;

    /**
     * @ORM\OneToMany(targetEntity=Panier::class, mappedBy="user", orphanRemoval=true)
     */
    private $paniers;

    /**
     * @ORM\OneToMany(targetEntity=Etoile::class, mappedBy="user", orphanRemoval=true)
     */
    private $etoiles;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="user", orphanRemoval=true)
     */
    private $commentaires;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Skateboard::class, mappedBy="user")
     */
    private $skateboards;

    public function __construct()
    {
        $this->adresses = new ArrayCollection();
        $this->wishlist = new ArrayCollection();
        $this->commandes = new ArrayCollection();
        $this->paniers = new ArrayCollection();
        $this->etoiles = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->skateboards = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getNewletter(): ?bool
    {
        return $this->newletter;
    }

    public function setNewletter(bool $newletter): self
    {
        $this->newletter = $newletter;

        return $this;
    }

    /**
     * @return Collection<int, Adresse>
     */
    public function getAdresses(): Collection
    {
        return $this->adresses;
    }

    public function addAdress(Adresse $adress): self
    {
        if (!$this->adresses->contains($adress)) {
            $this->adresses[] = $adress;
            $adress->setUser($this);
        }

        return $this;
    }

    public function removeAdress(Adresse $adress): self
    {
        if ($this->adresses->removeElement($adress)) {
            // set the owning side to null (unless already changed)
            if ($adress->getUser() === $this) {
                $adress->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Produit>
     */
    public function getWishlist(): Collection
    {
        return $this->wishlist;
    }

    public function addWishlist(Produit $wishlist): self
    {
        if (!$this->wishlist->contains($wishlist)) {
            $this->wishlist[] = $wishlist;
        }

        return $this;
    }

    public function removeWishlist(Produit $wishlist): self
    {
        $this->wishlist->removeElement($wishlist);

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Panier>
     */
    public function getPaniers(): Collection
    {
        return $this->paniers;
    }

    public function addPanier(Panier $panier): self
    {
        if (!$this->paniers->contains($panier)) {
            $this->paniers[] = $panier;
            $panier->setUser($this);
        }

        return $this;
    }

    public function removePanier(Panier $panier): self
    {
        if ($this->paniers->removeElement($panier)) {
            // set the owning side to null (unless already changed)
            if ($panier->getUser() === $this) {
                $panier->setUser(null);
            }
        }

        return $this;
    }

    public function getPaniersTotal(): int
    {
        $commandes = $this->getCommandes();
        $nbCommande = count($commandes);

        if ($nbCommande === 1) {
            $commande = $commandes[0];
        } else {
            $commande = $commandes[$nbCommande-1];
        }

        $return = 0;
        foreach ($commande->getPaniers() as $panier) {
            $return += $panier->getQte();
        }

        return $return;
    }

    /**
     * @return Collection<int, Etoile>
     */
    public function getEtoiles(): Collection
    {
        return $this->etoiles;
    }

    public function addEtoile(Etoile $etoile): self
    {
        if (!$this->etoiles->contains($etoile)) {
            $this->etoiles[] = $etoile;
            $etoile->setUser($this);
        }

        return $this;
    }

    public function removeEtoile(Etoile $etoile): self
    {
        if ($this->etoiles->removeElement($etoile)) {
            // set the owning side to null (unless already changed)
            if ($etoile->getUser() === $this) {
                $etoile->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setUser($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getUser() === $this) {
                $commentaire->setUser(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {

templates/shop/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Boutique{% endblock %}

{% block body %}
<h1 class="center titre">Boutique</h1>
<div class="form-full" id="sortBar">
    {{ form_start(sortBarForm) }}

    {{ form_label(sortBarForm.categorie) }}
    {{ form_widget(sortBarForm.categorie, {'attr': {'value': app.session.get('filter').categorie} }) }} {# MARCHE PAS CAR SELECT #}

    {{ form_label(sortBarForm.promo) }}
    {{ form_widget(sortBarForm.promo, {'attr': {'checked': app.session.get('filter').promo} }) }}

    {{ form_label(sortBarForm.prixUn) }}
    {{ form_widget(sortBarForm.prixUn, {'attr': {'value': app.session.get('filter').prixUn} }) }}

    {{ form_label(sortBarForm.prixDeux) }}
    {{ form_widget(sortBarForm.prixDeux, {'attr': {'value': app.session.get('filter').prixDeux} }) }} €

    {{ form_widget(sortBarForm.filtrer) }}
    
    {{ form_end(sortBarForm) }}
</div>

<div class="card-list-shop">
    {% for produit in produits %}
        {% set cat = produit.categorie.nom %}
        <div class="card">
            <a href="{{ path("show_shop", {'slug':produit.slug}) }}" class="mya"><img src="{{ asset('img_produit/' ~ produit.image) }}" alt="{{ produit.slug }}">
            <p>{{ produit.nom }}</p></a>
            <div>
                <span>Taille :{{ produit.taille }}</span>
                <span class="price">{{ produit.prix }} €</span>
            </div>
            <div>
                <span><i class="fa-solid fa-star star"></i>{{ (produit.averageEtoiles == 0) ? "New" : produit.averageEtoiles }}</span>

                {% if app.session.get("builder")[cat] %}
                    {% if app.session.get("builder")[cat].nom is same as(produit.nom) %}
                        <a href="{{ path("del_builder", {'slug':produit.slug}) }}"><i class="fa-solid fa-screwdriver mya"></i></a>
                    {% else %}
                        <a href="{{ path("add_builder", {'slug':produit.slug}) }}"><i class="fa-solid fa-screwdriver"></i></a>
                    {% endif %}
                {% else %}
                    <a href="{{ path("add_builder", {'slug':produit.slug}) }}"><i class="fa-solid fa-screwdriver"></i></a>
                {% endif %}

                {% if app.user and produit in app.user.wishlist %}
                    <a href="{{ path("del_wishlist", {'slug':produit.slug}) }}"><i class="fa-regular fa-heart mya"></i></a>
                {% else %}
                    <a href="{{ path("add_wishlist", {'slug':produit.slug}) }}"><i class="fa-regular fa-heart"></i></a>
                {% endif %}
                <a href="{{ path("add_panier", {'slug':produit.slug}) }}"><i class="fa-solid fa-cart-shopping"></i></a>
            </div>
        </div>
    {% endfor %}
</div>

<div class="center" id="pagination">
     <ul>
        <li class="{{ (page == 1) ? 'disabled' : '' }}"><a href="{{ path("page_shop", {'page':page-1}) }}">Préc</a></li>
        {% for i in 1..nbPages %}
            <li><a href="{{ path("page_shop", {'page':i}) }}">{{ i }}</a></li>
        {% endfor %}
        <li class="{{ (page == nbPages) ? 'disabled' : '' }}"><a href="{{ path("page_shop", {'page':page+1}) }}">Suiv</a></li>
    </ul>
</div>
{% endblock %}

templates/shop/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ produit }}{% endblock %}

{% block body %}
<h1 class="center titre">{{ produit }}</h1>

<section id="show-shop-box">
    <div>
        <img src="{{ asset('img_produit/' ~ produit.image) }}" alt="image produit">
    </div>
    <div id="show-shop-descri">
        <p class="center p-auto">{{ produit.description }}</p>
        <p class="center p-auto">
            Taille : {{ produit.taille }}<br>
            Categorie : {{ produit.categorie }}<br>
            Prix : <span class="price">{{ produit.prix }} €</span><br>
        </p>
        <div>
            {% if app.session.get("builder")[produit.categorie.nom] != null %}
                {% if app.session.get("builder")[produit.categorie.nom].nom is same as(produit.nom) %}
                    <a href="{{ path("del_builder", {'slug':produit.slug}) }}"><i class="fa-solid fa-screwdriver fa-2xl mya"></i></a>
                {% else %}
                    <a href="{{ path("add_builder", {'slug':produit.slug}) }}"><i class="fa-solid fa-screwdriver fa-2xl"></i></a>
                {% endif %}
            {% else %}
                <a href="{{ path("add_builder", {'slug':produit.slug}) }}"><i class="fa-solid fa-screwdriver fa-2xl"></i></a>
            {% endif %}

            {% if app.user and produit in app.user.wishlist %}
                <a href="{{ path("del_wishlist", {'slug':produit.slug}) }}"><i class="fa-regular fa-heart fa-2xl a-delete"></i></a>
            {% else %}
                <a href="{{ path("add_wishlist", {'slug':produit.slug}) }}"><i class="fa-regular fa-heart fa-2xl"></i></a>
            {% endif %}

            <a href="{{ path("add_panier", {'slug':produit.slug}) }}"><i class="fa-solid fa-cart-shopping fa-2xl"></i></a>
        </div>
    </div>
</section>
<section id="show-shop-star" class="titre">
    <div>
    {% if app.user %}
        {% if vote != null %}
            {% for i in 1..5 %}
                {% if i <= vote.note %}
                    <a class="star-gray" href="{{ path("edit_etoile", {'slug':produit.slug, 'note':i}) }}"><i class="fa-solid fa-star fa-2xl star" id="star{{ i }}"></i>  </a>
                {% else %}
                    <a class="star-gray" href="{{ path("edit_etoile", {'slug':produit.slug, 'note':i}) }}"><i class="fa-solid fa-star fa-2xl star-gray" id="star{{ i }}"></i>  </a>
                {% endif %}
            {% endfor %}
        {% endif %}
    
        {% if vote == null %}
            <a class="star-gray" href="{{ path("app_etoile", {'slug':produit.slug, 'note':1}) }}"><i class="fa-solid fa-star fa-2xl star" id="star1"></i>  </a>
            <a class="star-gray" href="{{ path("app_etoile", {'slug':produit.slug, 'note':2}) }}"><i class="fa-solid fa-star fa-2xl star" id="star2"></i>  </a>
            <a class="star-gray" href="{{ path("app_etoile", {'slug':produit.slug, 'note':3}) }}"><i class="fa-solid fa-star fa-2xl star" id="star3"></i>  </a>
            <a class="star-gray" href="{{ path("app_etoile", {'slug':produit.slug, 'note':4}) }}"><i class="fa-solid fa-star fa-2xl star" id="star4"></i>  </a>
            <a class="star-gray" href="{{ path("app_etoile", {'slug':produit.slug, 'note':5}) }}"><i class="fa-solid fa-star fa-2xl star" id="star5"></i>  </a>
        {% endif %}
    {% endif %}    
    </div>
    <p>{{ produit.etoiles|length }} {{ (produit.etoiles|length > 1) ? "votes" : "vote" }} (note <i class="fa-solid fa-star star"></i> : {{ produit.averageEtoiles }} / 5)</p>
</section>
<hr>
<section>
    <h2 class="center">Commentaires</h2>
    
    {% if app.user %}
    <div class="center">
        {{ form_start(commentaireForm) }}
        {{ form_widget(commentaireForm.commentaire) }}
        {{ form_end(commentaireForm) }}
    </div>
    {% endif %}
    <div id="show-shop-comment">
    {% for comment in commentaire %}
        <div>
            <p class="p-auto"><i class="fa-solid fa-circle-user"></i> <strong>{{ comment.user }}</strong> ({{ comment.createdAt|date('d-m-Y') }}) : <br>
            {{ comment }} 
            {% if app.user is same as(comment.user) %}
                <br><a href="{{ path("del_comment", {'id':comment.id}) }}" class="a-delete">Supprimer</a>
            {% endif %}    
            </p>
        </div>
    {% endfor %}
    </div>
</section>
<script src="{{ asset('js/etoile.js') }}"></script>
{% endblock %}